variables:
    IMAGE_NAME: phyllisn/juice-shop-demo
    IMAGE_TAG: juice-shop-1.0

stages:
    - cache
    - test
    - build

create_cache:
    image: node:18-bullseye
    stage: cache
    script:
        - yarn install
    cache:
        key:
            files:
                - yarn.lock
        paths:
            - node_modules/
            - yarn.lock
            - .yarn
        policy: pull-push

yarn_test:
    image: node:18-bullseye
    stage: test
    script:
        - yarn install
        - yarn test
    cache:
        key:
            files:
                - yarn.lock
        paths:
            - node_modules/
            - yarn.lock
            - .yarn
        policy: pull

gitleaks:
    stage: test
    image:
        name: zricethezav/gitleaks
        entrypoint: [""] # will not execute gitleaks immediately, waits until script is called
    script:
        - gitleaks detect --verbose --source .

build_image:
    stage: build
    image: docker:24
    services:
        - docker:24-dind
    variables:
        DOCKER_PASS: JXYZ17345GHI
        DOCKER_USER: phyllisn
    before_script:
        - echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
    script:
        - docker build -t $IMAGE_NAME:$IMAGE_TAG .
        - docker push $IMAGE_NAME:$IMAGE_TAG